Initial addition of reflector
lsst-ts/ts_config_mtcalsys pull request #23
Opened 2024-06-07 19:11 UTC by JosephParsons

2024-06-25 11:54 UTC, couger01 requested changes, later dismissed
I think the MTReflector configuration needs to have the real production values even if they are not well known yet.

2024-06-25 11:54 UTC, couger01 commented on MTReflector/v1/_init.yaml
This file should contain production values only.

2024-06-25 11:54 UTC, couger01 commented on MTReflector/v1/_summit.yaml
This file should contain values pertaining to the summit only.

2024-06-25 11:54 UTC, couger01 commented on MTReflector/v1/_tucson.yaml
This file should contain values pertaining to the Tucson Test Stand only.

2024-06-25 11:54 UTC, couger01 commented on towncrier.toml
Add an empty line at the end of this file.

2024-11-05 18:49 UTC, wvreeven approved these changes
LGTM

2025-01-20 15:33 UTC, merged